<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/*
|--------------------------------------------------------------------------
| Verdict — Initial schema
|--------------------------------------------------------------------------
|
| One consolidated migration for the full schema as it exists at cutover from
| the Node backend. Subsequent schema changes will get their own migration
| files (the normal Laravel pattern).
|
| Why one big migration instead of one-per-table:
|
|   This is a port of an already-finalised schema, not the evolutionary
|   history of how it got there. Splitting into 8 files would add noise
|   without value. Future changes (Batch 3+ improvements) get their own
|   sequential migration files.
|
| For existing installs (where the Node backend already created these tables):
|
|   php artisan migrate:install
|   # then mark this migration as applied without re-running:
|   php artisan tinker
|   >>> DB::table('migrations')->insert([
|   ...   'migration' => '2026_05_15_000001_create_initial_schema',
|   ...   'batch'     => 1,
|   ... ]);
|
| Uses raw SQL via DB::statement() instead of Schema::create() for most
| tables. Reasons:
|   1. Several tables have composite primary keys that Schema::create()
|      expresses awkwardly.
|   2. Several columns use SQLite-specific DEFAULT (datetime('now'))
|      defaults which Schema::create() can't represent directly.
|   3. Copying the literal CREATE TABLE strings from the Node backend's
|      database.ts guarantees byte-identical schemas — no chance of subtle
|      drift between Schema-builder output and the original.
|
| Indexes use Schema::table()->index() for legibility — those compile to
| identical CREATE INDEX statements regardless.
*/

return new class extends Migration
{
    /**
     * Run the migration — create all tables and indexes.
     *
     * Wrapped in DB::transaction so a partial failure rolls back instead of
     * leaving the schema half-applied. SQLite supports DDL inside
     * transactions (unlike some MySQL versions) so this works as expected.
     */
    public function up(): void
    {
        DB::transaction(function (): void {
            $this->createDevicesTable();
            $this->createUsageTable();
            $this->createPanelOpensTable();
            $this->createRequestLogsTable();
            $this->createSettingsTable();
            $this->createWebhookEventsTable();
            $this->createEmailVerificationsTable();
            $this->createEmailOutboxTable();
            $this->createIndexes();
        });
    }

    /**
     * Reverse the migration. Drops in reverse-dependency order — usage and
     * panel_opens reference devices.id via FK, so they must drop first.
     *
     * SQLite enforces foreign keys only when PRAGMA foreign_keys=ON. Laravel
     * sets this via config/database.php's `foreign_key_constraints` option.
     */
    public function down(): void
    {
        Schema::dropIfExists('email_outbox');
        Schema::dropIfExists('email_verifications');
        Schema::dropIfExists('webhook_events');
        Schema::dropIfExists('settings');
        Schema::dropIfExists('request_logs');
        Schema::dropIfExists('panel_opens');
        Schema::dropIfExists('usage');
        Schema::dropIfExists('devices');
    }

    // ────────────────────────────────────────────────────────────────────────
    // Table definitions
    // ────────────────────────────────────────────────────────────────────────

    /**
     * devices — one row per extension install.
     *
     * id is a UUID v4 generated by the extension on first install.
     * email is OPTIONAL — populated when the user starts a trial or saves
     *     their address. NULL is normal.
     * tier ∈ {'free', 'pro'} — the STORED tier. The effective tier
     *     (free | trial | pro) is computed at read time by getEffectiveTier()
     *     which factors in trial_started_at and subscription_status.
     * tier_override — admin override (NULL or 'pro'). When set, beats the
     *     normal tier-resolution logic. Used to comp specific accounts.
     * subscription_id — LemonSqueezy subscription ID, NULL for non-paying users.
     * subscription_status — most recent LS status: active | cancelled |
     *     past_due | expired | refunded | paused.
     * subscription_ends_at — paid-through date. For cancelled subscriptions
     *     this is when the user actually loses Pro access.
     * trial_started_at — when the user activated their 7-day trial. Once set,
     *     the user can never start another trial (one per email, enforced
     *     at the email level by activateTrial()).
     * past_due_at — when LS first reported a payment failure on this
     *     subscription. Stays set across multiple LS retries (see
     *     updateDeviceSubscription's IS NULL guard) so the grace period
     *     measures from the FIRST failure, not the most recent.
     *
     * Inline column definitions (rather than the Node backend's evolutionary
     * ALTER TABLE chain) — semantically identical, simpler to read.
     */
    private function createDevicesTable(): void
    {
        DB::statement(<<<'SQL'
            CREATE TABLE devices (
                id                   TEXT PRIMARY KEY,
                email                TEXT DEFAULT NULL,
                tier                 TEXT DEFAULT 'free',
                tier_override        TEXT DEFAULT NULL,
                subscription_id      TEXT DEFAULT NULL,
                subscription_status  TEXT DEFAULT NULL,
                subscription_ends_at TEXT DEFAULT NULL,
                trial_started_at     TEXT DEFAULT NULL,
                past_due_at          TEXT DEFAULT NULL,
                first_seen           TEXT NOT NULL DEFAULT (datetime('now')),
                last_seen            TEXT NOT NULL DEFAULT (datetime('now'))
            )
        SQL);
    }

    /**
     * usage — per-device, per-day API call counters.
     *
     * Composite PK (device_id, date) means there's at most one row per
     * (device, day). Incrementing happens via:
     *   INSERT INTO usage (device_id, jobs_scored) VALUES (?, ?)
     *   ON CONFLICT(device_id, date) DO UPDATE
     *       SET jobs_scored = jobs_scored + excluded.jobs_scored
     *
     * jobs_scored counts individual job cards scored (not API batch calls).
     * Renamed from batch_calls in the Node backend — fresh installs get
     * the right name directly here.
     *
     * FK to devices(id) is enforced via PRAGMA foreign_keys = ON.
     */
    private function createUsageTable(): void
    {
        DB::statement(<<<'SQL'
            CREATE TABLE usage (
                device_id     TEXT NOT NULL REFERENCES devices(id),
                date          TEXT NOT NULL DEFAULT (date('now')),
                jobs_scored   INTEGER NOT NULL DEFAULT 0,
                analyze_calls INTEGER NOT NULL DEFAULT 0,
                profile_calls INTEGER NOT NULL DEFAULT 0,
                PRIMARY KEY (device_id, date)
            )
        SQL);
    }

    /**
     * panel_opens — one row per (device, day, distinct job) the user opened.
     *
     * Composite PK (device_id, date, job_id) is the uniqueness constraint —
     * INSERT OR IGNORE on duplicate is a silent no-op so the same job
     * re-opened on the same day costs only one slot. PanelController checks
     * existence before counting.
     *
     * Note: empty job_id is REJECTED at the router level (M10 fix from
     * Batch 2). Previously the Node backend substituted a random UUID,
     * which silently inflated quota usage.
     */
    private function createPanelOpensTable(): void
    {
        DB::statement(<<<'SQL'
            CREATE TABLE panel_opens (
                device_id TEXT NOT NULL,
                date      TEXT NOT NULL DEFAULT (date('now')),
                job_id    TEXT NOT NULL,
                opened_at TEXT NOT NULL DEFAULT (datetime('now')),
                PRIMARY KEY (device_id, date, job_id)
            )
        SQL);
    }

    /**
     * request_logs — every API request, used for admin /admin/logs and
     * /admin/latency dashboards and for error-rate alerting.
     *
     * 30-day retention enforced by App\Console\Commands\CleanupLogs (P10).
     *
     * id is the request's correlation UUID (set by middleware). device_id
     * is NULL for requests that failed auth before reaching a controller.
     * error is NULL on success; otherwise a short error code string.
     */
    private function createRequestLogsTable(): void
    {
        DB::statement(<<<'SQL'
            CREATE TABLE request_logs (
                id         TEXT PRIMARY KEY,
                device_id  TEXT,
                endpoint   TEXT NOT NULL,
                latency_ms INTEGER NOT NULL,
                status     INTEGER NOT NULL,
                error      TEXT    DEFAULT NULL,
                created_at TEXT    NOT NULL DEFAULT (datetime('now'))
            )
        SQL);
    }

    /**
     * settings — generic key/value store for config that needs to be runtime-
     * mutable without a deploy. Examples:
     *   subscriptions_enabled — global kill-switch for the paywall
     *   disposable_email_domains — comma-separated blocklist
     *   admin_lockout_ip:* — brute-force protection state (P9)
     *
     * value is always TEXT — callers parse JSON if needed. Cheap, simple,
     * indexed for lookup via the PK.
     */
    private function createSettingsTable(): void
    {
        Schema::create('settings', function ($table): void {
            $table->string('key')->primary();
            $table->text('value');
        });
    }

    /**
     * webhook_events — idempotency guard for LemonSqueezy webhook deliveries.
     *
     * (provider, event_id) is the dedup key. A retry of the same event
     * INSERT-OR-IGNOREs into a no-op so we don't double-apply state changes
     * (e.g. re-stamping past_due_at, undoing a cancellation).
     *
     * 30-day retention via CleanupLogs (P10). LS doesn't retry past ~24
     * hours so 30 days is comfortable headroom for audit purposes.
     */
    private function createWebhookEventsTable(): void
    {
        DB::statement(<<<'SQL'
            CREATE TABLE webhook_events (
                provider    TEXT NOT NULL,
                event_id    TEXT NOT NULL,
                event_name  TEXT,
                received_at TEXT NOT NULL DEFAULT (datetime('now')),
                PRIMARY KEY (provider, event_id)
            )
        SQL);
    }

    /**
     * email_verifications — short-lived 6-digit codes for the subscription
     * restore flow (C3 / H3 fix from Batch 2).
     *
     * Codes are stored hashed (sha256 hex). 10-minute expiry, 5-attempt cap,
     * single-use (consumed_at set on first success). The router enforces
     * a max-3-pending-codes-per-email policy via pendingVerificationsForEmail().
     *
     * device_id binds the verification to the requesting device — a
     * different device cannot redeem someone else's intercepted code.
     *
     * purpose discriminates flows ('restore' today, 'login' later, etc.).
     */
    private function createEmailVerificationsTable(): void
    {
        DB::statement(<<<'SQL'
            CREATE TABLE email_verifications (
                id            TEXT PRIMARY KEY,
                email         TEXT NOT NULL,
                device_id     TEXT NOT NULL,
                purpose       TEXT NOT NULL,
                code_hash     TEXT NOT NULL,
                attempts      INTEGER NOT NULL DEFAULT 0,
                created_at    TEXT NOT NULL DEFAULT (datetime('now')),
                expires_at    TEXT NOT NULL,
                consumed_at   TEXT
            )
        SQL);
    }

    /**
     * email_outbox — audit log of every email queued for sending.
     *
     * During stub phase (pre-Batch 7) actual delivery happens by operator
     * console-copy; this table records what was queued. Once Batch 7 lands,
     * the real sender will set delivered_at = now() on successful SMTP.
     * delivered_at IS NULL means "queued, not yet sent".
     */
    private function createEmailOutboxTable(): void
    {
        DB::statement(<<<'SQL'
            CREATE TABLE email_outbox (
                id           TEXT PRIMARY KEY,
                kind         TEXT NOT NULL,
                to_email     TEXT NOT NULL,
                subject      TEXT NOT NULL,
                body         TEXT NOT NULL,
                queued_at    TEXT NOT NULL DEFAULT (datetime('now')),
                delivered_at TEXT
            )
        SQL);
    }

    /**
     * All indexes in one place, in the same order as the Node backend
     * creates them. Index names are kept identical (idx_usage_date, etc.)
     * so any production debugging that relied on EXPLAIN QUERY PLAN output
     * remains familiar.
     */
    private function createIndexes(): void
    {
        // usage — for date-range scans in /admin/daily
        Schema::table('usage', fn ($t) => $t->index('date', 'idx_usage_date'));

        // request_logs — three indexes for the three filters /admin/logs uses
        Schema::table('request_logs', function ($t): void {
            $t->index('created_at', 'idx_logs_created');
            $t->index('device_id',  'idx_logs_device');
            $t->index('status',     'idx_logs_status');
        });

        // panel_opens — for the per-device daily count query
        Schema::table('panel_opens', fn ($t) => $t->index(['device_id', 'date'], 'idx_panel_device'));

        // devices — for getDeviceByEmail() lookup
        Schema::table('devices', fn ($t) => $t->index('email', 'idx_devices_email'));

        // webhook_events — for retention cleanup
        Schema::table('webhook_events', fn ($t) => $t->index('received_at', 'idx_webhook_received'));

        // email_verifications — composite for pendingVerificationsForEmail
        // and verifyAndConsume's "latest unconsumed code" lookup
        Schema::table('email_verifications', function ($t): void {
            $t->index(['email', 'purpose'], 'idx_email_verif_email');
            $t->index('expires_at',          'idx_email_verif_expires');
        });

        // email_outbox — for retention cleanup
        Schema::table('email_outbox', fn ($t) => $t->index('queued_at', 'idx_email_outbox_queued'));
    }
};
