<?php

declare(strict_types=1);

namespace App\Models;

use App\Support\Limits;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * App\Models\Device
 *
 * One row per extension install. id is a UUID v4 generated by the extension
 * on first install and sent as the X-Device-ID header on every request.
 *
 * Central model — every authenticated request touches it. Most of the
 * domain logic that operates on a device lives here as instance methods
 * rather than in services, so controllers stay thin.
 *
 * @property string                  $id
 * @property string|null             $email
 * @property string                  $tier                   Stored tier: 'free' or 'pro'
 * @property string|null             $tier_override          Admin override: null or 'pro'
 * @property string|null             $subscription_id
 * @property string|null             $subscription_status    LS status: active|cancelled|past_due|expired|refunded|paused
 * @property CarbonImmutable|null    $subscription_ends_at
 * @property CarbonImmutable|null    $trial_started_at
 * @property CarbonImmutable|null    $past_due_at
 * @property CarbonImmutable         $first_seen
 * @property CarbonImmutable         $last_seen
 */
final class Device extends Model
{
    protected $table = 'devices';

    /**
     * The primary key is the extension-generated UUID, NOT auto-incrementing.
     * Without these three properties, Eloquent assumes id is an integer and
     * Device::find('uuid-string-here') silently returns null.
     */
    protected $primaryKey   = 'id';
    public    $incrementing = false;
    protected $keyType      = 'string';

    /**
     * The Node backend uses custom column names first_seen / last_seen
     * instead of Laravel's standard created_at / updated_at, so disable the
     * automatic timestamps. We populate them via SQLite DEFAULT clauses in
     * the migration and via the `touch()` method below where needed.
     */
    public $timestamps = false;

    /**
     * Mass-assignable on writes via Device::create() / ->fill().
     * Empty array because we set fields explicitly in service code —
     * mass-assignment vulnerabilities aren't a risk here (no user input
     * is ever bulk-assigned to a Device) but explicit is better than
     * guarded-by-default-fillable-by-default-when-empty Eloquent magic.
     */
    protected $fillable = [
        'id', 'email', 'tier', 'tier_override',
        'subscription_id', 'subscription_status', 'subscription_ends_at',
        'trial_started_at', 'past_due_at',
        'first_seen', 'last_seen',
    ];

    /**
     * SQLite stores datetimes as ISO-8601 strings. Carbon's default datetime
     * cast handles 'YYYY-MM-DD HH:MM:SS' format correctly. Five datetime
     * columns, all nullable except first_seen / last_seen.
     */
    protected function casts(): array
    {
        return [
            'subscription_ends_at' => 'immutable_datetime',
            'trial_started_at'    => 'immutable_datetime',
            'past_due_at'         => 'immutable_datetime',
            'first_seen'          => 'immutable_datetime',
            'last_seen'           => 'immutable_datetime',
        ];
    }

    // ────────────────────────────────────────────────────────────────────────
    // Domain logic — tier resolution
    // ────────────────────────────────────────────────────────────────────────

    /**
     * Compute the effective tier enforced for this device RIGHT NOW.
     *
     * Port of getEffectiveTier() from the Node backend's database.ts.
     * Priority order (first match wins):
     *
     *   1. Admin tier_override = 'pro'         → 'pro'   (always wins)
     *   2. Global subscriptions_enabled=false  → 'pro'   (admin kill-switch)
     *   3. Within 7-day trial window            → 'trial'
     *   4. subscription_status = 'active'       → 'pro'
     *   5. subscription_status = 'past_due' AND within PAST_DUE_GRACE_DAYS → 'pro'
     *   6. subscription_status = 'cancelled' AND ends_at in future → 'pro'
     *   7. Otherwise                            → 'free'
     *
     * IMPORTANT: this is a METHOD, not an accessor (effective_tier attribute),
     * because the answer depends on the current time. An accessor would
     * confuse callers into thinking it's a stored value and not realising
     * that calling it 24 hours apart can return different values.
     *
     * @return 'free'|'trial'|'pro'
     */
    public function effectiveTier(): string
    {
        // 1. Admin override wins.
        if ($this->tier_override === 'pro') {
            return 'pro';
        }

        // 2. Global kill-switch: when subscriptions are disabled, everyone is Pro.
        if (! Setting::subscriptionsEnabled()) {
            return 'pro';
        }

        // 3. Active trial: started < TRIAL_DAYS days ago.
        if ($this->isTrialActive()) {
            return 'trial';
        }

        // 4-6. Subscription states. Only check if the stored tier is 'pro'
        //      (i.e. they bought at some point). A user who never bought
        //      can't have a non-null subscription_status.
        if ($this->tier === 'pro') {
            if ($this->subscription_status === 'active') {
                return 'pro';
            }

            // past_due with grace period.
            // Legacy rows that pre-date the past_due_at column will have
            // status='past_due' but past_due_at=null. Trust LS and stay
            // Pro; expireStaleSubscriptions (P10) will catch up.
            if ($this->subscription_status === 'past_due') {
                if ($this->past_due_at === null) {
                    return 'pro';
                }
                $graceEnd = $this->past_due_at->addDays(Limits::PAST_DUE_GRACE_DAYS);
                if (now()->lt($graceEnd)) {
                    return 'pro';
                }
                // Grace expired — fall through to free.
            }

            // Cancelled but paid through period end.
            if ($this->subscription_status === 'cancelled'
                && $this->subscription_ends_at !== null
                && $this->subscription_ends_at->gt(now())
            ) {
                return 'pro';
            }
        }

        return 'free';
    }

    /**
     * True if the device started a trial less than TRIAL_DAYS days ago.
     * False if no trial started or the trial has expired.
     */
    public function isTrialActive(): bool
    {
        if ($this->trial_started_at === null) {
            return false;
        }
        $trialEnd = $this->trial_started_at->addDays(Limits::TRIAL_DAYS);
        return now()->lt($trialEnd);
    }

    /**
     * Days remaining in the current trial (1-based, always at least 1 while
     * active). Returns null if no trial is currently active.
     *
     * 1-based rather than 0-based because the popup displays "X days left"
     * to the user and "0 days left" would be confusing.
     */
    public function trialDaysLeft(): ?int
    {
        if (! $this->isTrialActive()) {
            return null;
        }
        /** @var CarbonImmutable $start — guaranteed non-null by isTrialActive() */
        $start    = $this->trial_started_at;
        $trialEnd = $start->addDays(Limits::TRIAL_DAYS);
        return max(1, (int) ceil(now()->diffInDays($trialEnd, false)));
    }

    /**
     * True if a fresh trial is available (free tier, never started one).
     * Used to decide whether to show the trial-CTA in popup/panel responses.
     */
    public function trialAvailable(): bool
    {
        return $this->effectiveTier() === 'free' && $this->trial_started_at === null;
    }

    // ────────────────────────────────────────────────────────────────────────
    // Relationships
    // ────────────────────────────────────────────────────────────────────────

    /**
     * Per-day usage rows. Use the helper for "today's row" so controllers
     * don't repeat the today()->toDateString() pattern.
     *
     * @return HasMany<Usage>
     */
    public function usage(): HasMany
    {
        return $this->hasMany(Usage::class, 'device_id', 'id');
    }

    /**
     * Today's usage row, creating it lazily if missing.
     *
     * The atomic INSERT...ON CONFLICT upsert in CheckRateLimit middleware
     * (P4) is how rows get created during normal traffic. This helper is
     * for READ paths (admin endpoints, subscription status) where we want
     * a row to exist even if the user hasn't made any tracked calls today.
     */
    public function usageToday(): Usage
    {
        $today = now()->toDateString();
        return $this->usage()->firstOrCreate(
            ['date' => $today],
            ['jobs_scored' => 0, 'analyze_calls' => 0, 'profile_calls' => 0]
        );
    }

    /**
     * Panel opens this device has performed. Used by the panel gate and by
     * admin endpoints showing per-device activity.
     *
     * @return HasMany<PanelOpen>
     */
    public function panelOpens(): HasMany
    {
        return $this->hasMany(PanelOpen::class, 'device_id', 'id');
    }

    // ────────────────────────────────────────────────────────────────────────
    // Query scopes
    // ────────────────────────────────────────────────────────────────────────

    /**
     * Filter to devices with an active or grace-period subscription.
     * Used by /api/subscription/restore — only restorable subs match.
     *
     * @param Builder<Device> $q
     */
    public function scopeWithRestorableSubscription(Builder $q): Builder
    {
        return $q->whereNotNull('subscription_id')
            ->whereIn('subscription_status', ['active', 'cancelled', 'past_due']);
    }

    /**
     * Filter to devices currently in their trial window.
     * Used by admin stats and (later) by the trial-ending-soon email job.
     *
     * @param Builder<Device> $q
     */
    public function scopeOnTrial(Builder $q): Builder
    {
        $cutoff = now()->subDays(Limits::TRIAL_DAYS)->toIso8601String();
        return $q->whereNotNull('trial_started_at')
            ->where('trial_started_at', '>', $cutoff);
    }

    /**
     * Find by email — case-insensitive lookup against the email column.
     *
     * Note: this does NOT canonicalize. Callers that need canonical-form
     * matching (foo+1@gmail.com == foo@gmail.com) should canonicalize the
     * input first via EmailHelper::canonicalize() (P4) before calling here.
     */
    public static function findByEmail(string $email): ?self
    {
        return static::query()
            ->whereRaw('LOWER(email) = LOWER(?)', [trim($email)])
            ->orderByDesc('last_seen')
            ->first();
    }

    /**
     * Touch the last_seen timestamp without bumping anything else.
     * Cheaper than save() — avoids loading/comparing all attributes.
     */
    public function touchLastSeen(): void
    {
        static::query()
            ->whereKey($this->getKey())
            ->update(['last_seen' => now()->toDateTimeString()]);
    }

    /**
     * Set the admin tier-override on this device.
     *
     * Used by /admin/devices/{id}/grant-pro (and its DELETE counterpart) to
     * comp accounts (early adopters, support refunds, etc.) The override
     * wins over the normal tier-resolution priority order in effectiveTier.
     *
     * Two valid values:
     *   'pro' — force device to Pro tier regardless of subscription state
     *   null  — clear the override, fall back to normal tier resolution
     *
     * Updates last_seen so the admin "subscription devices" list shows
     * recent activity on the row.
     */
    public function setTierOverride(?string $value): void
    {
        if ($value !== null && $value !== 'pro') {
            throw new \InvalidArgumentException(
                "setTierOverride: only null or 'pro' allowed, got '{$value}'"
            );
        }

        $this->update([
            'tier_override' => $value,
            'last_seen'     => now()->toDateTimeString(),
        ]);
    }
}
